<?php
namespace Iankibet\Shbackend\Tests;

class TestCase extends \Orchestra\Testbench\TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function getPackageProviders($app)
    {
        return [
            \Iankibet\Shbackend\SharaServiceProvider::class
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        //perform environment setup
    }

    protected function defineEnvironment($app)
    {
        // Setup default database to use sqlite :memory:
        $app['config']->set('database.default', 'sqlite');
        $app['config']->set('database.connections.sqlite', [
            'driver'   => 'sqlite',
            'database' => ':memory:',
            'prefix'   => '',
        ]);
    }

    protected function defineDatabaseMigrations()
    {
        $this->loadLaravelMigrations();
        $this->artisan('migrate:refresh', ['--database' => 'sqlite'])->run();
    }
}
